version: '3.8'

services:
  app:
    image: golang:1.21.0
    container_name: krepu_golang_echo_app
    working_dir: /app
    restart: always
    volumes:
      - ${PWD}:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - ${PWD}/.env
    environment:
      - DB_HOST=krepu_postgres_db
    command: >
      bash -c "sleep 10 && go run main.go"
    networks:
      - krepu-network
    depends_on:
      - postgres_db

  postgres_db:
    container_name: krepu_postgres_db
    image: postgres:9.6-alpine
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGPORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgresVolumeKrepu:/var/lib/postgresql/data
    networks:
      - krepu-network

networks:
  krepu-network:

volumes:
  postgresVolumeKrepu: